
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage


OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path(r"D:\Final Year Project\Project\NeuraScan\GUI\assets\frame0")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)


window = Tk()

window.geometry("1920x1080")
window.configure(bg = "#2A2A2A")


canvas = Canvas(
    window,
    bg = "#2A2A2A",
    height = 1080,
    width = 1920,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

canvas.place(x = 0, y = 0)

# GREY BACKGROUND SQUARE 1
image_image_14 = PhotoImage(
    file=relative_to_assets("GreyDecorSq1.png"))
image_14 = canvas.create_image(
    1550.0,
    750.0,
    image=image_image_14
)

# GREY BACKGROUND SQUARE 2
image_image_15 = PhotoImage(
    file=relative_to_assets("GreyDecorSq2.png"))
image_15 = canvas.create_image(
    1580.0,
    820.0,
    image=image_image_15
)

# WHITE DESCRIPTION BOX
canvas.create_rectangle(
    0.0,
    108.0,
    272.0,
    1123.0,
    fill="#FFFFFF",
    outline="")

# WHAT IS NEURASCAN TEXT
image_image_2 = PhotoImage(
    file=relative_to_assets("What is NeuraScan_.png"))
image_2 = canvas.create_image(
    120.0,
    180.0,
    image=image_image_2
)

# NEURASCAN DESCRIPTION
image_image_1 = PhotoImage(
    file=relative_to_assets("NeuraScan is an advanced deep learning software solution designed to analyze MRI brain scans with the purpose of predicting the severity of Alzheimer's disease present in the scan. Users can conveniently upload JPG.png")
)
image_1 = canvas.create_image(
    130.0,
    600.0,
    image=image_image_1
)

# BLUE HEADER RECTANGLE
canvas.create_rectangle(
    0.0,
    0.0,
    1920.0,
    127.0,
    fill="#00A3FF",
    outline="")

# NEURASCAN LOGO
image_image_4 = PhotoImage(
    file=relative_to_assets("NeuraScan.png"))
image_4 = canvas.create_image(
    350.0,
    65.0,
    image=image_image_4
)

# NEURASCAN SYMBOL
image_image_5 = PhotoImage(
    file=relative_to_assets("Artificial Intelligence.png"))
image_5 = canvas.create_image(
    130.0,
    65.0,
    image=image_image_5
)

# LEFT OUTPUT RECTANGLE
image_image_6 = PhotoImage(
    file=relative_to_assets("OutputRight.png"))
image_6 = canvas.create_image(
    670.0,
    700.0,
    image=image_image_6
)

# RIGHT OUTPUT RECTANGLE
image_image_7 = PhotoImage(
    file=relative_to_assets("OutputRight.png"))
image_7 = canvas.create_image(
    1450.0,
    700.0,
    image=image_image_7
)

# PREDICTION IS TEXT
image_image_3 = PhotoImage(
    file=relative_to_assets("Prediction is_.png"))
image_3 = canvas.create_image(
    510.0,
    375.0,
    image=image_image_3
)

# HEADER DECORATIONS
# BRAIN
image_image_10 = PhotoImage(
    file=relative_to_assets("Brain.png"))
image_10 = canvas.create_image(
    1480.0,
    70.0,
    image=image_image_10
)

# SECOND BRAIN
image_image_11 = PhotoImage(
    file=relative_to_assets("Critical Thinking.png"))
image_11 = canvas.create_image(
    1580.0,
    55.0,
    image=image_image_11
)

# ROBOT
image_image_12 = PhotoImage(
    file=relative_to_assets("Bot.png"))
image_12 = canvas.create_image(
    1680.0,
    65.0,
    image=image_image_12
)

# MACHINE LEARNING
image_image_13 = PhotoImage(
    file=relative_to_assets("Machine Learning.png"))
image_13 = canvas.create_image(
    1800.0,
    70.0,
    image=image_image_13
)
# UPLOAD SCAN BUTTON
image_image_8 = PhotoImage(
    file=relative_to_assets("ScanButton.png"))
image_8 = canvas.create_image(
    1010.0,
    240.0,
    image=image_image_8
)

# UPLOAD SCAN TEXT
image_image_9 = PhotoImage(
    file=relative_to_assets("Upload Scan.png"))
image_9  = canvas.create_image(
    1010.0,
    240.0,
    image=image_image_9
)

window.resizable(False, False)
window.mainloop()
